version: 2
jobs:
  build:
    working_directory: ~/django-beam
    docker:
      - image: circleci/python:3.6
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - checkout
      - run: pip install tox && tox
